version: '3'
services:
  api:
    build: .
    container_name: api
    environment:
      - DATABASE_PASSWORD=mysecretpassword
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:10.6
    container_name: db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data